// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Entities.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("race");
                });

            modelBuilder.Entity("Entities.Models.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("simulation");
                });

            modelBuilder.Entity("Entities.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ManucaturingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("VehicleTypeName");

                    b.ToTable("vehicle");
                });

            modelBuilder.Entity("Entities.Models.VehicleStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("CurrentSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Distance")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("HournsUtilFixed")
                        .HasColumnType("REAL");

                    b.Property<ushort>("Malfunctions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ReadyToStart");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("vehicle_statistic");
                });

            modelBuilder.Entity("Entities.Models.VehicleType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte>("MaxSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PercentageOfHeavyMalfunctionsPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PercentageOfLightMalfunctionsPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RepairmentTimeInHovers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuperType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("vehicle_type");

                    b.HasData(
                        new
                        {
                            Name = "sportsCar",
                            MaxSpeed = (byte)140,
                            PercentageOfHeavyMalfunctionsPerHour = (byte)2,
                            PercentageOfLightMalfunctionsPerHour = (byte)12,
                            RepairmentTimeInHovers = (byte)5,
                            SuperType = "car"
                        },
                        new
                        {
                            Name = "terrainCar",
                            MaxSpeed = (byte)100,
                            PercentageOfHeavyMalfunctionsPerHour = (byte)1,
                            PercentageOfLightMalfunctionsPerHour = (byte)3,
                            RepairmentTimeInHovers = (byte)5,
                            SuperType = "car"
                        },
                        new
                        {
                            Name = "truck",
                            MaxSpeed = (byte)80,
                            PercentageOfHeavyMalfunctionsPerHour = (byte)4,
                            PercentageOfLightMalfunctionsPerHour = (byte)6,
                            RepairmentTimeInHovers = (byte)7,
                            SuperType = "truck"
                        },
                        new
                        {
                            Name = "crossMotorcycle",
                            MaxSpeed = (byte)85,
                            PercentageOfHeavyMalfunctionsPerHour = (byte)2,
                            PercentageOfLightMalfunctionsPerHour = (byte)3,
                            RepairmentTimeInHovers = (byte)3,
                            SuperType = "motorcycle"
                        },
                        new
                        {
                            Name = "sportMotorcycle",
                            MaxSpeed = (byte)130,
                            PercentageOfHeavyMalfunctionsPerHour = (byte)10,
                            PercentageOfLightMalfunctionsPerHour = (byte)18,
                            RepairmentTimeInHovers = (byte)3,
                            SuperType = "motorcycle"
                        });
                });

            modelBuilder.Entity("Entities.Models.Simulation", b =>
                {
                    b.HasOne("Entities.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Vehicle", b =>
                {
                    b.HasOne("Entities.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.VehicleStatistic", b =>
                {
                    b.HasOne("Entities.Models.Vehicle", "Vehicle")
                        .WithOne("VehicleStatistic")
                        .HasForeignKey("Entities.Models.VehicleStatistic", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
